export const moviesDatas = [
    {
        "id":0,
        "MovieName":"The Shawshank Redemption",
        "genre":"Drama",
        "image":"https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
        "about":"Эхнэрээ алсан хилс хэрэгт ял авч, шоронд орсон Энди шоронд өөрийнхөөрөө амьдрах гэж хичээнэ. Өмнөх ажлын туршлага дээрээ тулгуурлан шоронд дасан зохицох түүний амьдрал, анд найзуудын нөхөрлөлийн түүхийг та  ШАУШЕНКЭЭС ОРГОСОН НЬ киноноос хүлээн авч үзээрэй.",
        "seat":[

            {
                "id":0,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":1,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":2,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":3,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":4,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":5,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":6,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":7,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":8,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":9,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":10,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":11,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":12,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":13,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":14,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":15,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":16,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":17,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":18,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":19,
                "isOrdered":false,
                "isOrdering":false,
            },
        ]
    },
    {
        "id":1,
        "MovieName":"The God Father",
        "genre":"Crime and Drama",
        "image":"https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "about":"1945-1955 он. Энэ бол Корлеоногийн гэр бүлийн гэмт хэргийн түүх. Өөрийг нь алах гэсэн оролдлогоос амьд үлдэж чадсан Вито цусан өшөө авах ажил эхлүүлнэ. Түүний гэр бүлийн гэмт хэргийн түүхийг та  ЗАГАЛМАЙЛСАН ЭЦЭГ киноноос хүлээн авч үзээрэй."
         ,
         "seat":[

            {
                "id":0,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":1,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":2,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":3,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":4,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":5,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":6,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":7,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":8,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":9,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":10,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":11,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":12,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":13,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":14,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":15,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":16,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":17,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":18,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":19,
                "isOrdered":false,
                "isOrdering":false,
            },
        ]
    },
    {
        "id":2,
        "MovieName":"Forrest Gump",
        "genre":"Drama and Romance",
        "image":"https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Forrest_Gump_poster.jpg/220px-Forrest_Gump_poster.jpg",
        "about":"The presidencies ,of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
        ,
         "seat":[

            {
                "id":0,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":1,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":2,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":3,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":4,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":5,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":6,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":7,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":8,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":9,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":10,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":11,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":12,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":13,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":14,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":15,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":16,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":17,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":18,
                "isOrdered":false,
                "isOrdering":false,
            },
            {
                "id":19,
                "isOrdered":false,
                "isOrdering":false,
            },
        ]
    }
]